server:
  port: ${BACKEND_PORT}

spring:
  application:
    name: Inclusive Traffic

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DEFAULT}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

mqtt:
  broker-url: ${MQTT_BROKER_URL}
  client-id: ${MQTT_CLIENT_ID}
  username: ${MQTT_USERNAME}
  password: ${MQTT_PASSWORD}
  topics:
    inbound-topic: ${INBOUND_TOPIC}
